In [1]:
# --------------------------------------------
# Assignment – Python (NumPy Basics)
# Student: Shubham Patial
# --------------------------------------------

In [2]:
import numpy as np

In [3]:
# Q1 – Create NumPy arrays (1D, 2D, 3D)

arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2,], [3, 4]], [[5, 6], [7, 8]]])
print(arr_1d)
print(arr_2d)
print(arr_3d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# Q2 – Print shape, size, and datatype of an array

print(arr_2d.shape)
print(arr_2d.size)
print(arr_2d.dtype)

(2, 3)
6
int64


In [6]:
# Q3 – Perform indexing and slicing on a NumPy array

indexing_arr = arr_1d[-1]
print(indexing_arr)
sliced_arr = arr_1d[1::2]
print(sliced_arr)


5
[2 4]


In [7]:

# Q4 – Perform arithmetic operations on arrays

squared_arr = arr_1d ** 2
print(squared_arr)

[ 1  4  9 16 25]


In [10]:

# Q5 – Use NumPy built-in functions (sum, mean, max, min)

sum = np.sum(arr_1d)
mean = np.mean(arr_1d)
max = np.max(arr_1d)
min = np.min(arr_1d)

print(sum)
print(mean)
print(max)
print(min)


15
3.0
5
1


In [14]:

# Q6 – Reshape a 1D array into 2D

arr = np.array([1,2,3,4,5,6])
print(arr)

reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Q7 – Combine arrays using horizontal & vertical stacking


In [ ]:
# Q8 – Apply Boolean conditions on NumPy arrays


In [26]:
# Q9 – Create arrays using zeros(), ones(), arange(), linspace()

zero_arr = np.zeros((2,2))
ones_arr = np.ones((2,2))
arrayy = np.arange(0,10,2)
line_space = np.linspace(1,10,5)
print(zero_arr)
print(ones_arr)
print(arrayy)
print(line_space)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]
[ 1.    3.25  5.5   7.75 10.  ]


In [29]:
# Q10 – Perform matrix multiplication using dot()
arr_1 = np.array([[1,2,3],[4,5,6]])
arr_2 = np.array([[7,8,9],[10,11,12]])

product_arry = arr_1 * arr_2
print(product_arry)

[[ 7 16 27]
 [40 55 72]]
