In [1]:
# --------------------------------------------
# Assignment – Python (NumPy Basics)
# Student: Shubham Patial
# --------------------------------------------

In [2]:
import numpy as np

In [3]:
# Q1 – Create NumPy arrays (1D, 2D, 3D)

arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2,], [3, 4]], [[5, 6], [7, 8]]])
print(arr_1d)
print(arr_2d)
print(arr_3d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# Q2 – Print shape, size, and datatype of an array

print(arr_2d.shape)
print(arr_2d.size)
print(arr_2d.dtype)

(2, 3)
6
int64


In [6]:
# Q3 – Perform indexing and slicing on a NumPy array

indexing_arr = arr_1d[-1]
print(indexing_arr)
sliced_arr = arr_1d[1::2]
print(sliced_arr)


5
[2 4]


In [7]:

# Q4 – Perform arithmetic operations on arrays

squared_arr = arr_1d ** 2
print(squared_arr)

[ 1  4  9 16 25]


In [ ]:

# Q5 – Use NumPy built-in functions (sum, mean, max, min)
# Your answer here:

# Q6 – Reshape a 1D array into 2D
# Your answer here:

# Q7 – Combine arrays using horizontal & vertical stacking
# Your answer here:

# Q8 – Apply Boolean conditions on NumPy arrays
# Your answer here:

# Q9 – Create arrays using zeros(), ones(), arange(), linspace()
# Your answer here:

# Q10 – Perform matrix multiplication using dot()
# Your answer here: